#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "game.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/COD.h"
#include "images/PLS.h"
#include "images/garbage.h"
#include "images/WINSC.h"
#include "images/LOSSSC.h"
#include "images/BOOM.h"
#include "images/C4.h"
// Load initial string
char start[] = "Press START to BEGIN!!!";
char win[] = "YOU DISABLED THE BOOM!!!";
char end[] = "BOMB EXPLODED!!!";
char boomA[] = "Press A to cut the red line!";
char boomB[] = "Press B to cut the blue line!";
char reset[] = "Want to reset? Press SELECT.";
char test1[] = "Press ENTER to TEST1.";
char pressUDLR[] = "Press button to move the box.";
char test2[] = "Press ENTER to TEST2.";
char resesting1[] = "resesting.";
char resesting2[] = "resesting..";
char resesting3[] = "resesting...";
// State controls
int play_mem = 0;
int start_mem = 0;
int end_mem = 0;
int test1_mem = 0;
int test2_mem = 0;
int x = 2;
int y = 2;
int count = 0;
// Load Test movement Box
struct box Box = {10, 10, 75, 115, RED};
struct box Box2 = {10, 10, 75, 115, GREEN};
// game body
int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCTL = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;
  // Load initial game state
  GBAState state = START;
  // Game body
  while (1) {
    // Load the current state of the buttons
    currentButtons = BUTTONS;
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    switch (state) {
      // Title screen
      case START: 
        // Display title screen
        if (start_mem == 0) {
          drawFullScreenImageDMA(COD);//display the fullscreen background
          drawString(150, 45, start, WHITE);//display the start game hint
          start_mem = 1;//stop redraw the image
        }
        // looking for start button to start the game
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          for (unsigned int i = 0; i < 5; i++) {
            fillScreenDMA(RED);
            delay(10);
            fillScreenDMA(WHITE);
            delay(10);
          }
          state = PLAY;
        }
        break;
      // defuse C4
      case PLAY:
        // C4 image display & information provided
        if (play_mem == 0) {
          fillScreenDMA(BLACK);
          drawImageDMA(20, 70, C4_WIDTH, C4_HEIGHT, C4);// This is C4 boom;
          drawString(120, 45, test1, WHITE);// Test1 string display
          drawString(130, 45, boomA, WHITE);// Defuse boom by cut red lime : press A
          drawString(140, 45, boomB, WHITE);// Defuse boom by cut blue lime : press B
          drawString(150, 45, reset, WHITE);// Reset image display
          play_mem = 1;
        }
        // looking for start button to start test1
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          state = TEST1;
        }
        // looking for A button to win the game
        if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
          drawFullScreenImageDMA(WINSC);
          delay(100);
          state = WIN;
        }
        // looking for B button to lose the game
        if (KEY_JUST_PRESSED(BUTTON_B, currentButtons, previousButtons)) {
          drawImageDMA(0, 60, BOOM_WIDTH, BOOM_HEIGHT, BOOM);
          delay(100);
          drawFullScreenImageDMA(LOSSSC);
          delay(100);
          state = LOSE;
        }
        // looking for reset button to reset the game to Title screen
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          fillScreenDMA(BLACK);
          resetFunction();
          displayResetInfor();
        }
        break;
      // movement
      case TEST1:
        if (test1_mem == 0) {
          test1_mem = 1;
          drawImageDMA(0, 0, GARBAGE_WIDTH, GARBAGE_HEIGHT, garbage);
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, Box.color);
        }
        // Move the box up by 10 pixels
        if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, BLACK);
          Box.row -= 10;
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, Box.color);
          char pressed[] = "UP";
          drawRectDMA(130, 45, 130, 10, BLACK);
          drawString(130, 45, pressed, GREEN);
        }
        // Move the box down by 10 pixels
        else if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, BLACK);
          Box.row += 10;
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, Box.color);
          char pressed[] = "DOWN";
          drawRectDMA(130, 45, 130, 10, BLACK);
          drawString(130, 45, pressed, GREEN);
        }
        // Move the box left by 10 pixels
        else if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, BLACK);
          Box.col -= 10;
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, Box.color);
          char pressed[] = "LEFT";
          drawRectDMA(130, 45, 130, 10, BLACK);
          drawString(130, 45, pressed, GREEN);
        }
        // Move the box right by 10 pixels
        else if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, BLACK);
          Box.col += 10;
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, Box.color);
          char pressed[] = "RIGHT";
          drawRectDMA(130, 45, 130, 10, BLACK);
          drawString(130, 45, pressed, GREEN);
        }
        drawString(120, 45, pressUDLR, GREEN);
        //
        drawString(140, 45, test2, WHITE);
        drawString(150, 45, reset, WHITE);
        // looking for reset button to reset the game to Title screen
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          fillScreenDMA(BLACK);
          resetFunction();
          displayResetInfor();
        }
        // looking for start button to start test2
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          state = TEST2;
        }
        break;
      // object collision & text
      case TEST2:
        if (test2_mem == 0) {
          test2_mem = 1;
          drawRectDMA(Box.row, Box.col, Box.width, Box.length, Box.color);
          drawRectDMA(Box2.row, Box2.col, Box2.width, Box2.length, Box2.color);
        }
        drawRectDMA(Box.row, Box.col, Box.width, Box.length, BLACK);
        drawRectDMA(Box2.row, Box2.col, Box2.width, Box2.length, BLACK);
        int move_x = randint(-5, 6);
        int move_y = randint(-5, 6);
        //Box1 random move with collision
        if (Box.row + move_x <= 0) {
          Box.row -= move_x;
          count++;
        } else if (Box.row + move_x + Box.length >= 160) {
          Box.row -= move_x;
          count++;
        } else {
          Box.row += move_x;
        }
        if (Box.col + move_y <= 0) {
          Box.col -= move_y;
          count++;
        } else if (Box.col + move_y + Box.length >= 240) {
          Box.col -= move_y;
          count++;
        } else {
          Box.col += move_y;
        }
        drawRectDMA(Box.row, Box.col, Box.width, Box.length, Box.color);
        //Box 2 random move with constant number
        if (Box2.row + x <= 0) {
          x = 2;
          count++;
        } else if (Box2.row + x + Box2.length >= 160) {
          x = -2;
          count++;
        }
        Box2.row += x;
        if (Box2.col + y <= 0) {
          y = 2;
          count++;
        } else if (Box2.col + y + Box2.length >= 240) {
          y = -2;
          count++;
        }
        Box2.col += y;
        drawRectDMA(Box2.row, Box2.col, Box2.width, Box2.length, Box2.color);
        delay(2);
        char countC[51];
        sprintf(countC, "Collision count: %d", count);
        drawRectDMA(130, 45, 130, 10, BLACK);
        drawString(130, 45, countC, GREEN);
        drawString(140, 45, test2, WHITE);
        drawString(150, 45, reset, WHITE);
        // looking for reset button to reset the game to Title screen
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          fillScreenDMA(BLACK);
          resetFunction();
          count = 0;
          displayResetInfor();
        }
        break;
      // C4 defused
      case WIN:
        // WIN screen
        if (end_mem == 0) {
          drawFullScreenImageDMA(PLS);
          drawString(130, 45, win, GREEN);
          drawString(150, 45, reset, WHITE);
          end_mem = 1;
        }
        // looking for reset button to reset the game to Title screen
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          fillScreenDMA(BLACK);
          resetFunction();
          displayResetInfor();
        }
        break;
      // C4 explode
      case LOSE:
        // LOSE screen
        if (end_mem == 0) {
          drawFullScreenImageDMA(PLS);
          drawString(130, 45, end, RED);
          drawString(150, 45, reset, WHITE);
          end_mem = 1;
        }
        // looking for reset button to reset the game to Title screen
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          fillScreenDMA(BLACK);
          resetFunction();
          displayResetInfor();
        }
        break;
    }
    // Store the current state of the buttons
    previousButtons = currentButtons;
    waitForVBlank();
  }
  // You can remove this once previousButtons is used
  return 0;
}
// Delay for about n tenths of a second
void delay(int n) {
  volatile int x = 0;
  for (int i = 0; i < n * 8000; i++) {
    x++;
  }
}
// Display the reset waiting screen
void displayResetInfor(void) {
  delay(10);
  drawString(130, 45, resesting1, WHITE);
  delay(20);
  drawString(130, 45, resesting2, WHITE);
  delay(20);
  drawString(130, 45, resesting3, WHITE);
  delay(20);
}
// Reset all the mem
void resetFunction(void) {
  play_mem = 0;
  start_mem = 0;
  end_mem = 0;
  test1_mem = 0;
  Box.col = 115;
  Box.row = 75;
}
